/*
 * tx_app.h
 *
 *  Created on: Jul 27, 2025
 *      Author: bens1
 */

#ifndef INC_TX_APP_H_
#define INC_TX_APP_H_

#ifdef __cplusplus
extern "C" {
#endif


#include "tx_api.h"


typedef enum {
    TX_STATUS_SUCCESS             = TX_SUCCESS,
    TX_STATUS_DELETED             = TX_DELETED,
    TX_STATUS_POOL_ERROR          = TX_POOL_ERROR,
    TX_STATUS_PTR_ERROR           = TX_PTR_ERROR,
    TX_STATUS_WAIT_ERROR          = TX_WAIT_ERROR,
    TX_STATUS_SIZE_ERROR          = TX_SIZE_ERROR,
    TX_STATUS_GROUP_ERROR         = TX_GROUP_ERROR,
    TX_STATUS_NO_EVENTS           = TX_NO_EVENTS,
    TX_STATUS_OPTION_ERROR        = TX_OPTION_ERROR,
    TX_STATUS_QUEUE_ERROR         = TX_QUEUE_ERROR,
    TX_STATUS_QUEUE_EMPTY         = TX_QUEUE_EMPTY,
    TX_STATUS_QUEUE_FULL          = TX_QUEUE_FULL,
    TX_STATUS_SEMAPHORE_ERROR     = TX_SEMAPHORE_ERROR,
    TX_STATUS_NO_INSTANCE         = TX_NO_INSTANCE,
    TX_STATUS_THREAD_ERROR        = TX_THREAD_ERROR,
    TX_STATUS_PRIORITY_ERROR      = TX_PRIORITY_ERROR,
    TX_STATUS_NO_MEMORY           = TX_NO_MEMORY,
    TX_STATUS_START_ERROR         = TX_START_ERROR,
    TX_STATUS_DELETE_ERROR        = TX_DELETE_ERROR,
    TX_STATUS_RESUME_ERROR        = TX_RESUME_ERROR,
    TX_STATUS_CALLER_ERROR        = TX_CALLER_ERROR,
    TX_STATUS_SUSPEND_ERROR       = TX_SUSPEND_ERROR,
    TX_STATUS_TIMER_ERROR         = TX_TIMER_ERROR,
    TX_STATUS_TICK_ERROR          = TX_TICK_ERROR,
    TX_STATUS_ACTIVATE_ERROR      = TX_ACTIVATE_ERROR,
    TX_STATUS_THRESH_ERROR        = TX_THRESH_ERROR,
    TX_STATUS_SUSPEND_LIFTED      = TX_SUSPEND_LIFTED,
    TX_STATUS_WAIT_ABORTED        = TX_WAIT_ABORTED,
    TX_STATUS_WAIT_ABORT_ERROR    = TX_WAIT_ABORT_ERROR,
    TX_STATUS_MUTEX_ERROR         = TX_MUTEX_ERROR,
    TX_STATUS_NOT_AVAILABLE       = TX_NOT_AVAILABLE,
    TX_STATUS_NOT_OWNED           = TX_NOT_OWNED,
    TX_STATUS_INHERIT_ERROR       = TX_INHERIT_ERROR,
    TX_STATUS_NOT_DONE            = TX_NOT_DONE,
    TX_STATUS_CEILING_EXCEEDED    = TX_CEILING_EXCEEDED,
    TX_STATUS_INVALID_CEILING     = TX_INVALID_CEILING,
    TX_STATUS_FEATURE_NOT_ENABLED = TX_FEATURE_NOT_ENABLED,
} tx_status_t;


void tx_setup(void *memory_ptr);


#ifdef __cplusplus
}
#endif

#endif /* INC_TX_APP_H_ */
